%Author: Lucas Simon Araújo
% Last modified: 12/04/2024

% Plot the static fields for the optimization benchmark 
% Ackley, Rastrigin, Schaffer, Griewank test functions
% Input: 
%            static field file generated by 'Stat_field.m'
% Output:
%           contour and surface plots
clear; close all; clc;

%-------------------------------------------------------
%User's entries
%choose function
opt = 'schaffer';
%record charts? (yes/no)
rec = 'no';
%which charts to plot?
Cont = 'yes';   %contour
Surf = 'yes';   %surface
%-------------------------------------------------------

%load data
switch opt
    case 'ackley'
        load ack_stat_field.mat field x1 x2
    case 'rastrigin'
        load ras_stat_field.mat field x1 x2
    case 'schaffer'
        load sch_stat_field.mat field x1 x2
    case 'griewank'
        load gri_stat_field.mat field x1 x2
end

%% Plotting
% CONTOUR
if Cont == "yes"
    a = figure;     a.Position = [ 338    42   723   642];
    figure(a)
    colormap("turbo")
    contourf(x1,x2,abs(field));
    colorbar;    %clim([min(real(y),[],"all") max(real(y),[],"all")])
    xlabel('x_1');    ylabel('x_2');
    % xticks(-5:5);    % xticks(-16:4:16);
    % yticks(-5:5)    % yticks(-16:4:16)
    box on;    axis equal;
    ax = gca;    ax.FontSize = 20;
    axis([x1(1) x1(end) x2(1) x2(end)])
end

% SURFACE
if Surf =="yes"
    b = figure;    b.Position = [ 338    42   723   642];
    figure(b)
    colormap("turbo")
    s = surf(x1,x2,abs(field));
    s.EdgeColor = 'none';    s.FaceColor = 'interp';
    colorbar
    xlabel('x_1');    ylabel('x_2');
    % box on;    % axis equal;
    ax = gca;    ax.FontSize = 20;
    axis([x1(1) x1(end) x2(1) x2(end)])
end

if rec == "yes"
    if opt == "ackley"
        saveas(a,'ack_stat_cont','epsc')
        saveas(b,'ack_stat_surf','epsc')
    elseif opt == "rastrigin"
        saveas(a,'ras_stat_cont','epsc')
        saveas(b,'ras_stat_surf','epsc')
    elseif opt == "schaffer"
        saveas(a,'sch_stat_cont','epsc')
        saveas(b,'sch_stat_surf','epsc')
    elseif opt == "griewank"
        saveas(a,'grie_stat_cont','epsc')
        saveas(b,'grie_stat_surf','epsc')
    end
end